#!/bin/sh

# https://github.com/OpenVPN/easy-rsa
# https://wiki.archlinux.org/index.php/Easy-RSA
# https://www.maths.tcd.ie/~fionn/misc/ec_vpn/

usage() {
    echo "Usage: $0 (client|server|ca) PKI_DIR COMMON_NAME"
    exit 1
}

create_ovpn() {
    local OVPN_DIR="${EASYRSA_PKI}/openvpn"
    local OVPN_FILE="${OVPN_DIR}/$1.ovpn"

    mkdir -p "${OVPN_DIR}"

    cat template.ovpn                   >   "${OVPN_FILE}"
    echo                                >>  "${OVPN_FILE}"
    echo "<ca>"                         >>  "${OVPN_FILE}"
    cat "${EASYRSA_PKI}/ca.crt"         >>  "${OVPN_FILE}"
    echo "</ca>"                        >>  "${OVPN_FILE}"
    echo                                >>  "${OVPN_FILE}"
    echo "<cert>"                       >>  "${OVPN_FILE}"
    cat "${EASYRSA_PKI}/issued/$1.crt"  >>  "${OVPN_FILE}"
    echo "</cert>"                      >>  "${OVPN_FILE}"
    echo                                >>  "${OVPN_FILE}"
    echo "<key>"                        >>  "${OVPN_FILE}"
    cat "${EASYRSA_PKI}/private/$1.key" >>  "${OVPN_FILE}"
    echo "</key>"                       >>  "${OVPN_FILE}"
}

create_client() {
    easyrsa build-client-full "$1"
    create_ovpn "$1"
}

create_server() {
    easyrsa build-server-full "$1" nopass
}

create_ca() {
    easyrsa init-pki
    EASYRSA_REQ_CN="$1" easyrsa --batch build-ca
}

export EASYRSA="$(dirname $0)"
X509_TYPE="$1"
export EASYRSA_PKI="$2"
COMMON_NAME="$3"

if [ -z "${X509_TYPE}" ] || [ -z "${EASYRSA_PKI}" ] || [ -z "${COMMON_NAME}" ] ; then
    usage
fi

case "${X509_TYPE}" in
    client) create_client "${COMMON_NAME}"  ;;
    server) create_server "${COMMON_NAME}"  ;;
    ca)     create_ca     "${COMMON_NAME}"  ;;
    *)      usage
esac
